# Generated by Django 4.2.4 on 2023-10-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
        ("bot_statistics", "0002_polloptionuserinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloptionuserinfo",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistic",
                to="polls.polloptions",
            ),
        ),
    ]
