# Generated by Django 4.2.4 on 2023-08-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stories_news", "0008_alter_storynews_position"),
        ("bot_statistics", "0002_postuserscount"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryNewsViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stories_news.storynews",
                    ),
                ),
            ],
        ),
    ]
