# Generated by Django 4.2.4 on 2023-08-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_product_category2"),
        ("bot_statistics", "0004_productviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productviews",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
