# Generated by Django 4.2.4 on 2023-08-18 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot_statistics", "0006_categoryviews"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoryviews",
            old_name="product",
            new_name="category",
        ),
    ]
