# Generated by Django 4.2.4 on 2023-08-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bot_statistics",
            "0008_categoryviews_created_at_polluserscount_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerChatRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.TextField()),
                ("manager", models.CharField(max_length=32)),
                ("bot_user", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
