# Generated by Django 4.2.4 on 2023-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_statistics", "0010_kprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="productviews",
            name="kp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productviews",
            name="manager_chat",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
