# Generated by Django 4.2.4 on 2023-09-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_category_position"),
        ("bot_statistics", "0011_productviews_kp_productviews_manager_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryviews",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="categories.category",
            ),
        ),
    ]
