# Generated by Django 4.2.4 on 2023-09-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stories_news", "0008_alter_storynews_position"),
        ("bot_statistics", "0012_alter_categoryviews_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storynewsviews",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="stories_news.storynews",
            ),
        ),
    ]
