# Generated by Django 4.2.4 on 2023-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.FileField(blank=True, upload_to="post_media/"),
        ),
    ]
