# Generated by Django 4.2.4 on 2023-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_post_media_postmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmedia",
            name="absolute_media_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
