# Generated by Django 4.2.4 on 2023-08-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0013_alter_extendeduser_user_delete_customuser"),
        ("posts", "0004_postmedia_absolute_media_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot_users.botusergroup",
            ),
        ),
    ]
