# Generated by Django 4.2.4 on 2023-08-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_post_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="total_media_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
