# Generated by Django 4.2.4 on 2023-08-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0014_alter_botuser_options_alter_botusergroup_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0009_post_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelOptions(
            name="postmedia",
            options={"verbose_name": "Медиа", "verbose_name_plural": "Медиа"},
        ),
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot_users.botusergroup",
                verbose_name="Группа пользователей бота",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="post",
            name="total_media_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Сколько фотографий загрузите?"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="absolute_media_path",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Абсолютный путь до медиа"
            ),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="media",
            field=models.FileField(
                blank=True, upload_to="post_media/", verbose_name="Медиа"
            ),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mediafiles",
                to="posts.post",
                verbose_name="Пост",
            ),
        ),
    ]
