# Generated by Django 4.2.4 on 2023-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_post_options_alter_postmedia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
