# Generated by Django 4.2.4 on 2023-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_post_scheduled_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время рассылки"
            ),
        ),
    ]
