# Generated by Django 4.2.4 on 2023-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_remove_post_total_media_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(
                default=None, null=True, verbose_name="Подтверждён"
            ),
        ),
    ]
