# Generated by Django 4.2.4 on 2024-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_alter_post_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
    ]
