# Generated by Django 4.2.4 on 2023-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="command",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterField(
            model_name="command",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="command",
            name="key",
            field=models.CharField(max_length=64, verbose_name="Ключ"),
        ),
        migrations.AlterField(
            model_name="command",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="command",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
