# Generated by Django 4.2.4 on 2023-08-17 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commands", "0002_alter_command_options_alter_command_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
