# Generated by Django 4.2.4 on 2023-08-17 05:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commands", "0003_command_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="command",
            name="content",
        ),
        migrations.AlterField(
            model_name="command",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
    ]
