# Generated by Django 4.2.4 on 2023-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0002_botuser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="botuser",
            name="username",
            field=models.CharField(default="None", max_length=128),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.CharField(max_length=128),
        ),
    ]
