# Generated by Django 4.2.4 on 2023-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0003_botuser_updated_at_botuser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="username",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
