# Generated by Django 4.2.4 on 2023-08-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0006_botusergroup_botuser_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botuser",
            name="group",
        ),
        migrations.AddField(
            model_name="botusergroup",
            name="members",
            field=models.ManyToManyField(related_name="groups", to="bot_users.botuser"),
        ),
    ]
