# Generated by Django 4.2.4 on 2023-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0007_remove_botuser_group_botusergroup_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusergroup",
            name="members",
            field=models.ManyToManyField(to="bot_users.botuser"),
        ),
    ]
