# Generated by Django 4.2.4 on 2023-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0008_alter_botusergroup_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botuser",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="botuser",
            name="last_interaction",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
