# Generated by Django 4.2.4 on 2023-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0013_alter_extendeduser_user_delete_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botuser",
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
        migrations.AlterModelOptions(
            name="botusergroup",
            options={
                "verbose_name": "Группа пользователей бота",
                "verbose_name_plural": "Группы пользователей бота",
            },
        ),
        migrations.AlterField(
            model_name="botuser",
            name="activated",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="company_name",
            field=models.CharField(max_length=128, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="last_interaction",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="manager",
            field=models.BooleanField(default=False, verbose_name="Менеджер"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="name",
            field=models.CharField(max_length=128, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="images", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Телеграм-ID"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Телеграм-юзернейм"
            ),
        ),
        migrations.AlterField(
            model_name="botusergroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="botusergroup",
            name="members",
            field=models.ManyToManyField(
                to="bot_users.botuser", verbose_name="Участники"
            ),
        ),
        migrations.AlterField(
            model_name="botusergroup",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="botusergroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
    ]
