# Generated by Django 4.2.4 on 2023-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0014_alter_botuser_options_alter_botusergroup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.CharField(
                default="Admin", max_length=128, unique=True, verbose_name="Телеграм-ID"
            ),
        ),
    ]
