# Generated by Django 4.2.4 on 2023-08-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_category_position"),
        ("bot_users", "0015_alter_botuser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
