# Generated by Django 4.2.4 on 2023-08-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0017_remove_botuser_category_extendeduser_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendeduser",
            name="bot_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot_users.botuser",
                verbose_name="Телеграм-пользователь менеджера",
            ),
        ),
    ]
