# Generated by Django 4.2.4 on 2023-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0018_alter_extendeduser_bot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Город"
            ),
        ),
    ]
