# Generated by Django 4.2.4 on 2023-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0019_botuser_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="product_manager",
            field=models.BooleanField(
                default=False, verbose_name="Менеджер по поиску товаров"
            ),
        ),
    ]
