# Generated by Django 4.2.4 on 2024-04-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0020_extendeduser_product_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="last_viewed_category_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="ID последней просмотренной категории",
            ),
        ),
    ]
