# Generated by Django 4.2.4 on 2023-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер позиции"
            ),
        ),
    ]
