# Generated by Django 4.2.4 on 2024-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0020_extendeduser_product_manager"),
        ("categories", "0004_category_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="categories",
                to="bot_users.botuser",
                verbose_name="Менеджеры",
            ),
        ),
    ]
