# Generated by Django 4.2.4 on 2024-02-19 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0005_category_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджеры",
            ),
        ),
    ]
