# Generated by Django 4.2.4 on 2023-08-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot_users", "0013_alter_extendeduser_user_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("options", models.TextField()),
                ("correct_answer", models.PositiveIntegerField()),
                ("approved", models.BooleanField(default=False)),
                ("total_media_count", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot_users.botusergroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(blank=True, upload_to="poll_media/")),
                ("absolute_media_path", models.CharField(blank=True, max_length=255)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediafiles",
                        to="polls.poll",
                    ),
                ),
            ],
        ),
    ]
