# Generated by Django 4.2.4 on 2023-10-09 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot_users", "0019_botuser_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время рассылки"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Подтверждён"),
                ),
                (
                    "correct_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ на правильный выбор"
                    ),
                ),
                (
                    "incorrect_message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ответ на неправильный выбор",
                    ),
                ),
                (
                    "option_message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ответ на выбор без правильных ответов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Создано"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot_users.botusergroup",
                        verbose_name="Группа пользователей бота",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.CreateModel(
            name="PollOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(max_length=128, verbose_name="Вариант ответа"),
                ),
                (
                    "correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Изменено"
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.poll",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="PollMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True, upload_to="poll_media/", verbose_name="Медиа"
                    ),
                ),
                (
                    "absolute_media_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Абсолютный путь до медиа",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Изменено"
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediafiles",
                        to="polls.poll",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа",
                "verbose_name_plural": "Медиа",
            },
        ),
    ]
