# Generated by Django 4.2.4 on 2023-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="correct_answer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
