# Generated by Django 4.2.4 on 2023-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_poll_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
