# Generated by Django 4.2.4 on 2023-08-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot_users", "0014_alter_botuser_options_alter_botusergroup_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0004_poll_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"verbose_name": "Опрос", "verbose_name_plural": "Опросы"},
        ),
        migrations.AlterModelOptions(
            name="pollmedia",
            options={"verbose_name": "Медиа", "verbose_name_plural": "Медиа"},
        ),
        migrations.AlterField(
            model_name="poll",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
        migrations.AlterField(
            model_name="poll",
            name="correct_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Правильный ответ(если пусто, то без правильных ответов)",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot_users.botusergroup",
                verbose_name="Группа пользователей бота",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="options",
            field=models.TextField(verbose_name="Варианты ответа"),
        ),
        migrations.AlterField(
            model_name="poll",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="poll",
            name="total_media_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Сколько фотографий загрузите?"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="pollmedia",
            name="absolute_media_path",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Абсолютный путь до медиа"
            ),
        ),
        migrations.AlterField(
            model_name="pollmedia",
            name="media",
            field=models.FileField(
                blank=True, upload_to="poll_media/", verbose_name="Медиа"
            ),
        ),
        migrations.AlterField(
            model_name="pollmedia",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mediafiles",
                to="polls.poll",
                verbose_name="Опрос",
            ),
        ),
    ]
