# Generated by Django 4.2.4 on 2023-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_alter_poll_options_alter_pollmedia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время рассылки"
            ),
        ),
    ]
