# Generated by Django 4.2.4 on 2023-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories_news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sort",
                    models.CharField(
                        choices=[("option1", "News"), ("option2", "Story")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Story and news",
                "verbose_name_plural": "Stories and news",
            },
        ),
        migrations.DeleteModel(
            name="StoryNew",
        ),
    ]
