# Generated by Django 4.2.4 on 2023-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories_news", "0002_storynews_delete_storynew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storynews",
            name="sort",
            field=models.CharField(
                choices=[("news", "News"), ("story", "Story")], max_length=10
            ),
        ),
    ]
