# Generated by Django 4.2.4 on 2023-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories_news", "0004_storynews_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="storynews",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
