# Generated by Django 4.2.4 on 2023-08-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stories_news",
            "0006_alter_storynews_options_alter_storynews_approved_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="storynews",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, default=1000, null=True, verbose_name="Номер позиции"
            ),
        ),
    ]
