# Generated by Django 4.2.4 on 2024-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories_news", "0008_alter_storynews_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storynews",
            options={
                "verbose_name": "Актуальный статус/Новость",
                "verbose_name_plural": "Актуальные статусы/Новости",
            },
        ),
        migrations.AlterField(
            model_name="storynews",
            name="sort",
            field=models.CharField(
                choices=[("news", "Новость"), ("story", "Актуальный статус")],
                max_length=10,
                verbose_name="Актуальный статус/Новость",
            ),
        ),
    ]
