# Generated by Django 4.2.4 on 2024-02-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XMLImportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_path",
                    models.CharField(max_length=255, verbose_name="Путь к папке"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                (
                    "first_import_time",
                    models.TimeField(verbose_name="Время первого импорта"),
                ),
                (
                    "second_import_time",
                    models.TimeField(verbose_name="Время второго импорта"),
                ),
            ],
        ),
    ]
