# Generated by Django 4.2.4 on 2024-03-20 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xml_import", "0002_alter_xmlimportsettings_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xmlimportsettings",
            name="first_import_time",
        ),
        migrations.RemoveField(
            model_name="xmlimportsettings",
            name="second_import_time",
        ),
    ]
