# Generated by Django 4.2.4 on 2024-03-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xml_import", "0003_remove_xmlimportsettings_first_import_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imported",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Импортировано товаров:"
                    ),
                ),
                (
                    "skipped",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Пропущено товаров:"
                    ),
                ),
            ],
        ),
    ]
