# Generated by Django 4.2.4 on 2024-03-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xml_import", "0004_importstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importstatistics",
            name="imported",
            field=models.IntegerField(default=0, verbose_name="Импортировано товаров:"),
        ),
        migrations.AlterField(
            model_name="importstatistics",
            name="skipped",
            field=models.IntegerField(default=0, verbose_name="Пропущено товаров:"),
        ),
    ]
