# Generated by Django 4.2.4 on 2024-03-20 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xml_import", "0005_alter_importstatistics_imported_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importstatistics",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 3, 20, 10, 24, 14, 947871, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
