# Generated by Django 4.2.4 on 2024-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xml_import", "0006_importstatistics_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importstatistics",
            options={
                "ordering": ["-date"],
                "verbose_name": "Статистика XML импорта",
                "verbose_name_plural": "Статистика XML импорта",
            },
        ),
        migrations.AddField(
            model_name="importstatistics",
            name="updated",
            field=models.IntegerField(default=0, verbose_name="Обновлено товаров"),
        ),
        migrations.AlterField(
            model_name="importstatistics",
            name="imported",
            field=models.IntegerField(default=0, verbose_name="Импортировано товаров"),
        ),
        migrations.AlterField(
            model_name="importstatistics",
            name="skipped",
            field=models.IntegerField(default=0, verbose_name="Пропущено товаров"),
        ),
    ]
