# Generated by Django 4.2.4 on 2023-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_equipment_product_manufacturer_product_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RUB", "rub"),
                    ("USD", "usd"),
                    ("EUR", "eur"),
                    ("CNY", "cny"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
