# Generated by Django 4.2.4 on 2023-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_currency_product_promotion_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
