# Generated by Django 4.2.4 on 2023-08-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options_alter_category_name_and_more"),
        ("products", "0008_alter_equipment_description_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "verbose_name": "Комплектация",
                "verbose_name_plural": "Комплектации",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Марка"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RUB", "rub"),
                    ("USD", "usd"),
                    ("EUR", "eur"),
                    ("CNY", "cny"),
                ],
                max_length=3,
                null=True,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.equipment",
                verbose_name="Комплектация",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="hide",
            field=models.BooleanField(default=False, verbose_name="Скрыть"),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Производитель"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="images", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_model",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Модель"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotion",
            field=models.BooleanField(default=False, verbose_name="Акция"),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotion_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание акции"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("instock", "В наличии"), ("supply", "Поставка")],
                max_length=10,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="product",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Год выпуска"
            ),
        ),
    ]
