# Generated by Django 4.2.4 on 2023-08-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options_alter_category_name_and_more"),
        ("products", "0009_alter_equipment_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products2",
                to="categories.category",
                verbose_name="Категория2",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.category",
                verbose_name="Категория",
            ),
        ),
    ]
