# Generated by Django 4.2.4 on 2023-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options_alter_category_name_and_more"),
        ("products", "0011_remove_product_category2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="product",
                to="categories.category",
                verbose_name="Категория",
            ),
        ),
    ]
