# Generated by Django 4.2.4 on 2023-08-17 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
    ]
