# Generated by Django 4.2.4 on 2023-08-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_product_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер позиции в категории"
            ),
        ),
    ]
