# Generated by Django 4.2.4 on 2023-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_product_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Страна производителя",
            ),
        ),
    ]
