# Generated by Django 4.2.4 on 2023-08-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_category_position"),
        ("products", "0017_alter_product_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products2",
                to="categories.category",
                verbose_name="Категория2",
            ),
        ),
    ]
