# Generated by Django 4.2.4 on 2023-08-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес для яндекс-картинки'),
        ),
    ]
