# Generated by Django 4.2.4 on 2023-08-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="species",
            field=models.CharField(
                blank=True,
                choices=[
                    ("truck", "Грузовик"),
                    ("pickup", "Пикап"),
                    ("dump", "Самосвал"),
                ],
                max_length=20,
                null=True,
                verbose_name="Вид техники",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wheels",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Колёсная формула"
            ),
        ),
    ]
