# Generated by Django 4.2.4 on 2023-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_product_species_product_wheels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="species",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Вид техники"
            ),
        ),
    ]
