# Generated by Django 4.2.4 on 2023-09-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_alter_product_species"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True, upload_to="product_media/", verbose_name="Медиа"
                    ),
                ),
                (
                    "absolute_media_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Абсолютный путь до медиа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediafiles",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа",
                "verbose_name_plural": "Медиа",
            },
        ),
    ]
