# Generated by Django 4.2.4 on 2023-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_productmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmedia",
            options={
                "verbose_name": "Дополнительные фото",
                "verbose_name_plural": "Дополнительные фото",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="kp",
            field=models.FileField(blank=True, null=True, upload_to="kp/"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="media",
            field=models.FileField(
                blank=True, upload_to="product_media/", verbose_name="Доп. фотки"
            ),
        ),
    ]
