# Generated by Django 4.2.4 on 2023-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_alter_productmedia_options_product_kp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kp_url",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Адрес для яндекс-файла",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kp",
            field=models.FileField(
                blank=True, null=True, upload_to="kp/", verbose_name="КП"
            ),
        ),
    ]
