# Generated by Django 4.2.4 on 2023-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_product_kp_url_alter_product_kp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Название"
            ),
        ),
    ]
