# Generated by Django 4.2.4 on 2023-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="media_url",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Адрес для яндекс-картинки",
            ),
        ),
    ]
