# Generated by Django 4.2.4 on 2024-02-06 07:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_alter_productmedia_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[1270, 600],
                upload_to="images",
                verbose_name="Фотография",
            ),
        ),
    ]
