# Generated by Django 4.2.4 on 2024-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0043_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AddField(
            model_name="product",
            name="char_id",
            field=models.CharField(
                max_length=128, blank=True, editable=False, null=True, verbose_name="Текстовый ID"
            ),
        ),
    ]
